services:
  database:
    image: postgres:latest
    container_name: api_todos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./src/scripts/sql:/docker-entrypoint-initdb.d
